version: '3.8'

services:
  nivora-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nivora-dashboard
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://10.241.197.145:8080
      - REDIS_URL=redis://nivora-redis:6379
      - REDIS_PASSWORD=nivora_redis_password
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./next.config.ts:/app/next.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - ./tailwind.config.js:/app/tailwind.config.js
    networks:
      - shared-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Note: Redis dependency is managed externally via docker-compose.redis.yml
    labels:
      - "com.nivora.service=dashboard"
      - "com.nivora.type=application"

  # Redis for caching and sessions (referenced from external compose)
  # Note: Redis is managed by docker-compose.redis.yml

volumes:
  nivora_dashboard_data:
    driver: local

networks:
  shared-network:
    external: true 